import cases


def function2(nums):
    """ To find the unit digit of product of some integers
        Args:
            nums: list of integers
        Returns:
            unit digit of the product of the given integers
    """

    unitProduct = 1

    for i in nums:
        unitProduct *= i % 10
        unitProduct %= 10

    return unitProduct


def testing(case):
    """ To test the answers generated by cases.generateData() 
        Args:
            case: case number of input-output pair
        Return:
            True, if the answer matches, else False
    """

    with open("input{}.txt".format(case), "r") as f:
        intList = [int(i) for i in f.readline().split()]

    out = function2(intList)

    with open("output{}.txt".format(case), "r") as f:
        if str(out) == f.readline().strip():
            return True
        else:
            return False


if __name__ == "__main__":
    # Generating data
    cases.generateData()

    # testing
    with open("index.txt", "r") as f:
        indexes = [i.strip() for i in f.readlines()]

    for i in indexes:
        if not testing(i):
            print("FAILED")
            break

    else:
        print("SUCCESS")
